import:
    cache-key: default
    file-type: auto
    force: false
    managed:
        authentication-flow: full
        client: full
        client-scope: full
        client-scope-mapping: full
        component: full
        group: full
        identity-provider: full
        identity-provider-mapper: full
        required-action: full
        role: full
        scope-mapping: full
        sub-component: full
    parallel: false
    remove-default-role-from-user: false
    skip-attributes-for-federated-user: false
    state: true
    state-encryption-salt: 2B521C795FBE2F2425DB150CD3700BA9
    sync-user-federation: false
    var-substitution: false
    var-substitution-in-variables: true
    var-substitution-prefix: $(
    var-substitution-suffix: )
    var-substitution-undefined-throws-exceptions: true
keycloak:
    availability-check:
        enabled: false
        retry-delay: 2s
        timeout: 120s
    client-id: admin-cli
    client-secret: ''
    grant-type: password
    login-realm: master
    ssl-verify: true
    user: admin
    version: '@keycloak.version@'
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration
    cache:
        type: NONE
    main:
        banner-mode: 'off'
        lazy-initialization: true
        log-startup-info: true
        web-application-type: NONE
