import:
    path: contrib/art-market-config/
keycloak:
    password: admin
    url: http://auth.jware.local:8989/auth/
    user: admin
spring:
    config:
        import: classpath:application-debug.properties
    output:
        ansi:
            enabled: ALWAYS
